### ISSUE TITLE
import problem with undefined symbol _ZNK6OPenMM

### ISSUE THREAD

**Issue by moradza** [pandegroup/openmm-nn#14]
I have a problem installing the openmm-nn. I have tensorflow C API as well as openmm.
As I try to import module I get segmentation fault (core dumped)

If I import siktm.openmm then import openmmnn I get following error

ImportError: /usr/local/lib/ibtensorflow.so.1: undefined symbol: _ZN10tensoflow10FileSystem20RecursivelyCreateDirERKSs

Import error also change to /usr/local/openmm/lib/libOpenMM.so: undefined symbol: _ZNK6OPenMM8Platform12createKernelERJNSt7__cxx1112vasic_stringICSt11char_traitsICESaIcEERNS_11ContextImplE

**Comment by moradza** [comment]
Do you guys have a plan to make these packages available through conda installation?

**Comment by jchodera** [comment]
I'm very much hoping we can! There are some technical issues we're sorting out right now regarding how we build conda packages, but once we've got that sorted, I think we should be able to provide these via conda.

Out of curiosity, how exactly did you install Tensorflow on your system?

**Comment by moradza** [comment]
That would be great, do you have any time frame for that? I am looking to do a project using NN force field. 
I installed using instruction on the tensorflow webpage,

sudo tar -C /usr/local -xzf (downloaded file)
sudo ldconfig

I tested so library is working, I also installed tensorflow using pip install tensorflow==1.15.0
same version as the downloaded file.

**Comment by peastman** [comment]
Yeah, there are... issues.  This requires the TensorFlow C API, which isn't conda installable.  Worse, it's incompatible with the Python API, so if you try to use them together you get a crash.  See https://github.com/tensorflow/tensorflow/issues/31932.  I opened that issue months ago, and I've gotten no response at all from the TensorFlow team.

I'm closing this issue since it's a duplicate of #8.  Let's continue the discussion there.  I see someone already posted advice there on how to fix this.
